[package]
name = "sandbox"
version = "0.1.0"
authors = ["Guillaume Guimond <guimog@gmail.com>"]

[dependencies]
phrases = { path = "../phrases" }
libc = "0.2.0"
#hello-world-derive = { path = "hello-world-derive" }
